spring.application.name=cloud-file-storage
server.url=${SERVER_URL}

# Storage конфигурация
app.bucket.name=user-files
app.root.template.name=folder-%d-path/

# Базовая конфигурация
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
logging.level.org.springframework.security=trace
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8

# File size/count настройки
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
server.tomcat.max-part-count=40

## Настройки драйвера
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate настройки
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# hikari Настройки
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.max-lifetime=1800000

# Liquibase настройки
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.drop-first=true

# Session настройки
spring.session.redis.repository-type=default
spring.session.timeout=1800
spring.session.redis.flush-mode=on-save
spring.session.redis.namespace=spring:session

# Redis настройки
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.database=0
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8

# Swagger настройки
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/index.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.cache.disabled=true